### ISSUE TITLE
【bounty】PlatON-Go Releases v1.1.2 英文校对

### ISSUE THREAD

**Issue by biganxin** [LatticeX-Foundation/dev-bounties#2]
## 概述
校对PlatON-Go Releases v1.1.2 版本发布更新日志英文https://github.com/PlatONnetwork/PlatON-Go/releases/tag/v1.1.2
中文参考：https://github.com/AlayaNetwork/Alaya-Go/releases/tag/v0.16.2

## 要求
将校对修正后的内容，通过Issue方式提交（PlatON-Go）

## 奖励
400LAT

## 报名和交付
仅接收一位报名，本帖回复“报名”+交付时间+奖励接收地址
交付：本帖回复校对修正issue的链接

**Comment by windrainice** [comment]
报名+2021-12-08交付+地址：lat1ptmpwv759k4x03rkvjs8pf3t6hf0h9g74xur40

交付内容：

**Comment by windrainice** [comment]
# Galileo Release(v1.1.2)

The Galileo (v1.1.2) release is a hotfix for an online issue [#1880](https://github.com/PlatONnetwork/PlatON-Go/issues/1880) that could cause verifier nodes to be slashed

## Bug-fixes

- Fix data inconsistency in concurrent cases due to the use of global random instance[PlatON-issue-1880](https://github.com/PlatONnetwork/PlatON-Go/issues/1880)

## Notes


When the seed of a random instance is contaminated by concurrency, there will be a 'BAD BLOCK' in the nodes' log. ***Besides,  the block will not be verified, resulting in failure to receive enough votes for the proposer's block**.* There are 3 possible situations as follows, 

- If the first block produced by the node is not affected, but the seed has been contaminated in subsequent blocks. The node's block production rate will be affected because the final confirmed block is less than 10, the expected number.

- According to the Giskard consensus mechanism, if the first block is contaminated by concurrency, the next blocks can be proposed without confirmation. Subsequently,  all blocks of the node in this round will not be confirmed, which will eventually result in 0 blocks proposed and the nodes being slashed.

- For non-block-producing nodes, the seed may be contaminated while verifying the block, resulting in failure to pass the block verification. Hence, the overall fault tolerance of the consensus will be reduced regarding that the contaminated node can't vote.

  In the above consideration, it is strongly recommended that all verifiers upgrade your node immediately.

**Comment by windrainice** [comment]
报名+2021-12-08交付+地址：lat1ptmpwv759k4x03rkvjs8pf3t6hf0h9g74xur40

交付内容：https://github.com/LatticeX-Foundation/dev-bounties/issues/2#issuecomment-988629196

**Comment by biganxin** [comment]
Thank you for your support, the reward has been applied and is expected to be paid within 7 working days
For queries, please contact Discord (Boney_bee#915)
